# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for Todo
  pod 'RealmSwift'
  pod "TinyConstraints"
  pod 'Layoutless'
  pod 'FSCalendar'
  pod 'Firebase/Analytics'
  pod 'Purchases'
  pod 'Firebase/Crashlytics'
  pod "GWInfinitePickerView"
  pod 'IQKeyboardManagerSwift'
  pod 'FBSDKCoreKit/Swift'
end
